include("atmosphere.jl")
include("getAIC.jl")
include("velocity3d.jl")
include("getAlpha.jl")
include("getLIC.jl")
include("getDIC.jl")
include("gen_geometry.jl")
include("getViscous.jl")
include("vortex.jl")
include("getWIC.jl")
include("Cdrag.jl")
include("Pdrag.jl")
include("getMIC.jl")
include("VLM.jl")

